/**
 * IDs de genListado para flujos de aprobación ACC/GVR e instancia de revisión.
 * Deben coincidir con la BD (ver seeds/acc_flujo_trabajo_aprobacion_listados.sql).
 *
 * Front: `front-visor-gvr/src/constants/listasOpciones.ts` (mismos valores).
 */
export const ID_LISTA_ACC_FLUJO_ESTADO = 24;
export const ID_LISTA_ACC_FLUJO_TIPO_INICIADOR = 25;
export const ID_LISTA_ACC_FLUJO_CONDICION_COPIA = 26;
export const ID_LISTA_ACC_FLUJO_MODALIDAD_REVISOR = 27;
export const ID_LISTA_ACC_FLUJO_ACCION_FINALIZAR = 28;
export const ID_LISTA_ACC_FLUJO_PASO_TIPO = 29;
export const ID_LISTA_ACC_FLUJO_EXIGENCIA_APROBACION = 30;
export const ID_LISTA_ACC_FLUJO_TIPO_VENCIMIENTO_PASO = 31;
export const ID_LISTA_ACC_FLUJO_MODO_REVISION_GRUPAL = 32;
export const ID_LISTA_ACC_FLUJO_TIPO_ASIGNACION = 33;
export const ID_LISTA_ACC_FLUJO_API_WORKFLOW_STATUS = 34;
export const ID_LISTA_ACC_FLUJO_API_VALOR_ESTADO_APROBACION = 35;
export const ID_LISTA_ACC_FLUJO_ALCANCE_ACTUALIZACION_ATRIBUTOS = 36;
export const ID_LISTA_ACC_FLUJO_TIPO_ATRIBUTO_REVISION = 37;
export const ID_LISTA_ACC_FLUJO_ICONO_ESTADO_REVISION = 38;
export const ID_LISTA_ACC_FLUJO_ESTADO_REGISTRO = 39;
export const ID_LISTA_ACC_FLUJO_PLANTILLA_PRESET = 40;
export const ID_LISTA_ACC_REVISION_ESTADO = 41;
export const ID_LISTA_ACC_REVISION_ARCHIVO_ESTADO_APROBACION = 42;
export const ID_LISTA_ACC_REVISION_PASO_PROGRESO_ESTADO = 43;
export const ID_LISTA_ACC_REVISION_TIPO_EVENTO = 44;

/** Todas las listas del módulo (útil para catálogos o validaciones). */
export const IDS_LISTAS_ACC_FLUJO_Y_REVISION: readonly number[] = [
  ID_LISTA_ACC_FLUJO_ESTADO,
  ID_LISTA_ACC_FLUJO_TIPO_INICIADOR,
  ID_LISTA_ACC_FLUJO_CONDICION_COPIA,
  ID_LISTA_ACC_FLUJO_MODALIDAD_REVISOR,
  ID_LISTA_ACC_FLUJO_ACCION_FINALIZAR,
  ID_LISTA_ACC_FLUJO_PASO_TIPO,
  ID_LISTA_ACC_FLUJO_EXIGENCIA_APROBACION,
  ID_LISTA_ACC_FLUJO_TIPO_VENCIMIENTO_PASO,
  ID_LISTA_ACC_FLUJO_MODO_REVISION_GRUPAL,
  ID_LISTA_ACC_FLUJO_TIPO_ASIGNACION,
  ID_LISTA_ACC_FLUJO_API_WORKFLOW_STATUS,
  ID_LISTA_ACC_FLUJO_API_VALOR_ESTADO_APROBACION,
  ID_LISTA_ACC_FLUJO_ALCANCE_ACTUALIZACION_ATRIBUTOS,
  ID_LISTA_ACC_FLUJO_TIPO_ATRIBUTO_REVISION,
  ID_LISTA_ACC_FLUJO_ICONO_ESTADO_REVISION,
  ID_LISTA_ACC_FLUJO_ESTADO_REGISTRO,
  ID_LISTA_ACC_FLUJO_PLANTILLA_PRESET,
  ID_LISTA_ACC_REVISION_ESTADO,
  ID_LISTA_ACC_REVISION_ARCHIVO_ESTADO_APROBACION,
  ID_LISTA_ACC_REVISION_PASO_PROGRESO_ESTADO,
  ID_LISTA_ACC_REVISION_TIPO_EVENTO,
];
